---
title: "Beats"
output:
  github_document: default
always_allow_html: true
---
```{r, echo=F, message=F, include=F}
devtools::load_all(".")
source('../code/plot.R')
source('../code/utils.R')
```

## At 0

```{r, echo=F, message=F}
P1 = mami.codi(0, 
               num_harmonics=1,
               verbose=T)
```

```{r, echo=F, message=F}
M2_skinny = mami.codi(c(0,1.9), 
                      num_harmonics=1,
                      verbose=T)
```


```{r, echo=F, message=F}
M2_fat = mami.codi(c(0,2.1), 
                   num_harmonics=1,
                   verbose=T)
```

```{r, echo=F}
tibble::tibble(
  interval=c('P1', 'M2 skinny', 'M2 FAT'),
  semitone=c(P1$frequencies[[1]] %>% hrep::freq_to_midi() %>% max() ,
             M2_skinny$frequencies[[1]] %>% hrep::freq_to_midi() %>% max() ,
             M2_fat$frequencies[[1]] %>% hrep::freq_to_midi() %>% max() ),
  beating=c(P1$beating, M2_skinny$beating, M2_fat$beating),
  wavelengths=c(toString(P1$wavelengths[[1]]), toString(M2_skinny$wavelengths[[1]]), 
                toString(M2_fat$wavelengths[[1]]))
)
```

## At 60

```{r, echo=F, message=F}
P1 = mami.codi(60, 
               num_harmonics=1,
               verbose=T)
```

```{r, echo=F, message=F}
M2_skinny = mami.codi(c(60,61.9), 
                      num_harmonics=1,
                      verbose=T)
```


```{r, echo=F, message=F}
M2_fat = mami.codi(c(60,62.1), 
                   num_harmonics=1,
                   verbose=T)
```

```{r, echo=F}
tibble::tibble(
  interval=c('P1', 'M2 skinny', 'M2 FAT'),
  semitone=c(P1$frequencies[[1]] %>% hrep::freq_to_midi() %>% max() - 60,
             M2_skinny$frequencies[[1]] %>% hrep::freq_to_midi() %>% max() - 60,
             M2_fat$frequencies[[1]] %>% hrep::freq_to_midi() %>% max() - 60),
  beating=c(P1$beating, M2_skinny$beating, M2_fat$beating),
  wavelengths=c(toString(P1$wavelengths[[1]]), toString(M2_skinny$wavelengths[[1]]), 
                toString(M2_fat$wavelengths[[1]]))
)
```


```{r, echo=F, message=F}
experiment.rds = '../data/input/Pure.rds'
grid = tidyr::expand_grid(
  interval = readRDS(experiment.rds)$profile$interval,
  num_harmonics=1,
  octave_ratio=2.0,
  timbre = 'Pure'
)

output = grid %>% purrr::pmap_dfr(\(interval,
                                    num_harmonics,
                                    octave_ratio,
                                    timbre) {
  
  study_chord = (60 + c(0, interval)) %>% hrep::sparse_fr_spectrum(
    num_harmonics = num_harmonics,
    octave_ratio  = octave_ratio,
    roll_off_dB   = 3.0
  )
  
  mami.codi.R::mami.codi(study_chord,
                         metadata = list(
                           num_harmonics       = num_harmonics,
                           octave_ratio        = octave_ratio,
                           semitone            = interval,
                           timbre              = timbre
                         ),
                         verbose=TRUE)
  
}, .progress=TRUE)
```

```{r, echo=F, message=F}
plot(output$beating)
```

```{r, echo=F}
dyads <- output %>% dplyr::rowwise() %>% dplyr::mutate(
  num_harmonics = metadata$num_harmonics,
  octave_ratio  = metadata$octave_ratio,
  semitone      = metadata$semitone,
  timbre        = metadata$timbre,
  label         = round(metadata$semitone),
  chord_max     = max(frequencies),
  chord_min     = min(frequencies),
  .before=1
)
```

```{r, echo=F}

chords <- dyads %>% dplyr::filter(timbre == 'Pure')

```

```{r, echo=F}

chords$consonance_z = z_scores(-chords$dissonance)
chords$major_z = z_scores(chords$majorness)
chords$space_consonance = -chords$space_dissonance
chords$time_consonance = -chords$time_dissonance
chords$space_consonance_z = z_scores(-chords$space_dissonance)
chords$time_consonance_z = z_scores(-chords$time_dissonance)
black_vlines  = c(7,12)
```

```{r, echo=F}
toString(chords$cochlear_amplifier_num_harmonics %>% unique)
```

```{r, echo=F}
default_cochlear_amplifier_num_harmonics()
```

```{r, echo=F}
plot_semitone_beating(chords, 'Beating',
                      include_points=T,include_line=F,
                      black_vlines=black_vlines)

```

```{r, echo=F, message=F}
C4_midi = 60
f_beat = 7 # Hz
C4_beat_midi = hrep::freq_to_midi(hrep::midi_to_freq(60) + f_beat)
duration = 3.0
num_harmonics = 5
tone_1 = hrep::sparse_fr_spectrum(c(C4_midi, C4_beat_midi), num_harmonics=num_harmonics) %>% hrep::wave(length_sec = duration)
tone_1  %>% hrep::play_wav(player = '/usr/bin/afplay')
```
