---
title: "Cochlea"
output:
  github_document: default
always_allow_html: true
---
```{r, echo=F, message=F, include=F}
devtools::load_all(".")
source('./man/code/plot.R')
source('./man/code/utils.R')
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "../figures/Cochlea-"
)
time = 2 * (1 / hrep::midi_to_freq(24))
plot_fundamental_wavelength <- function(midi) {
  freq = hrep::midi_to_freq(midi)
  c_sound = 343
  wavelength = c_sound / freq
  wavenumber = (2 * pi) / wavelength
  tibble::tibble(
    meters=seq(0, wavelength ,0.001),
    amplitude=sin(wavenumber * meters)
  ) %>% ggplot2::ggplot(ggplot2::aes(meters, amplitude)) +
    ggplot2::geom_line()
}
```

```{r, echo=T, message=F, include=T}
midi=24
plot_fundamental_wavelength(midi)
```

```{r, echo=T, message=F, include=T}
C1 = c(midi) %>% hrep::sparse_fr_spectrum(num_harmonics=5)
C1 %>% plot(cochlea =T,ggplot=T,xlim=c(0,100))
```

```{r, echo=T, message=F, include=T}
C1 %>% hrep::wave(length_sec=time) %>% plot(ggplot=T)
```

```{r, echo=T, message=F, include=T}
C1 %>% plot(ggplot=T)
```

```{r, echo=T, message=F, include=T}
midi=60
plot_fundamental_wavelength(midi)
```

```{r, echo=T, message=F, include=T}
C4 = c(midi) %>% hrep::sparse_fr_spectrum(num_harmonics=5)
C4 %>% plot(cochlea =T,ggplot=T,xlim=c(0,100))
```

```{r, echo=T, message=F, include=T}
C4 %>% hrep::wave(length_sec=time) %>% plot(ggplot=T)
```

```{r, echo=T, message=F, include=T}
C4 %>% plot(ggplot=T)
```

```{r, echo=T, message=F, include=T}
midi=96
plot_fundamental_wavelength(midi)
```

```{r, echo=F, message=F, include=T}
C7 = c(midi) %>% hrep::sparse_fr_spectrum(num_harmonics=5)
C7 %>% plot(cochlea =T,ggplot=T,xlim=c(0,100))
```

```{r, echo=T, message=F, include=T}
C7 %>% hrep::wave(length_sec=time) %>% plot(ggplot=T)
```

```{r, echo=F, message=F, include=T}
C7 %>% plot(ggplot=T)
```
