---
title: "f0 and l0"
output:
  github_document: default
always_allow_html: true
---
```{r, echo=F, message=F, include=F}
devtools::load_all(".")
source('./man/code/plot.R')
source('./man/code/utils.R')
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "../figures/f0-l0-"
)
knitr::opts_chunk$set(dev = 'png')
```
```{r, echo=F, message=F}
temporal_standard_deviation = default_standard_deviation() / (2*pi)
```


```{r, echo=F, message=F}
mami_codi_harmonics <- function(h) mami.codi(c(60), verbose=T, num_harmonics = h,
                                             temporal_standard_deviation = temporal_standard_deviation)
P1 = 1:20  %>% purrr::map_dfr(mami_codi_harmonics)
```

## Tight Temporal, Loose Spatial

Temporal standard_deviation: `r P1$temporal_standard_deviation %>% unique()`\
Spatial  standard_deviation: `r P1$spatial_standard_deviation %>% unique()`

### P1

```{r, echo=F, message=F}
P1 %>% 
  dplyr::mutate(
    T_f = 1 / f0, 
    T_l = l0 / speed_of_sound
    ) %>%
  dplyr::select(f0,l0,T_f,T_l)
```

### P4

```{r, echo=F, message=F}
mami_codi_harmonics <- function(h) mami.codi(c(60,65), verbose=T, num_harmonics = h,
                                             temporal_standard_deviation = temporal_standard_deviation)
1:20  %>% purrr::map_dfr(mami_codi_harmonics) %>% 
  dplyr::mutate(
    T_f = 1 / f0, 
    T_l = l0 / speed_of_sound
    ) %>%
  dplyr::select(f0,l0,T_f,T_l)
```

### P5

```{r, echo=F, message=F}
mami_codi_harmonics <- function(h) mami.codi(c(60,67), verbose=T, num_harmonics = h,
                                             temporal_standard_deviation = temporal_standard_deviation)
1:20  %>% purrr::map_dfr(mami_codi_harmonics) %>% 
  dplyr::mutate(
    T_f = 1 / f0, 
    T_l = l0 / speed_of_sound
    ) %>%
  dplyr::select(f0,l0,T_f,T_l)
```

```{r, echo=F, message=F}
mami_codi_harmonics <- function(h) mami.codi(c(60), verbose=T, num_harmonics = h)
P1 = 1:20  %>% purrr::map_dfr(mami_codi_harmonics)
```

## Even Steven

Temporal standard_deviation: `r P1$temporal_standard_deviation %>% unique()`\
Spatial  standard_deviation: `r P1$spatial_standard_deviation %>% unique()`

### P1

```{r, echo=F, message=F}
P1 %>% 
  dplyr::mutate(
    T_f = 1 / f0, 
    T_l = l0 / speed_of_sound
    ) %>%
  dplyr::select(f0,l0,T_f,T_l)
```

### P4

```{r, echo=F, message=F}
mami_codi_harmonics <- function(h) mami.codi(c(60,65), verbose=T, num_harmonics = h)
1:20  %>% purrr::map_dfr(mami_codi_harmonics) %>% 
  dplyr::mutate(
    T_f = 1 / f0, 
    T_l = l0 / speed_of_sound
    ) %>%
  dplyr::select(f0,l0,T_f,T_l)
```

### P5

```{r, echo=F, message=F}
mami_codi_harmonics <- function(h) mami.codi(c(60,67), verbose=T, num_harmonics = h)
1:20  %>% purrr::map_dfr(mami_codi_harmonics) %>% 
  dplyr::mutate(
    T_f = 1 / f0, 
    T_l = l0 / speed_of_sound
    ) %>%
  dplyr::select(f0,l0,T_f,T_l)
```
