---
title: "Fundamental Frequencies"
output:
  github_document: default
always_allow_html: true
---
```{r, echo=F, message=F, include=F}
devtools::load_all(".")
devtools::load_all(".")
source('../code/plot.R')
source('../code/utils.R')
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "../figures/Fundamental-Frequencies-"
)
```

```{r, echo=F, message=F, include=T, results='asis'}
# Define the intervals
intervals <- list(
  # consonant intervals
  M3 = c(60, 64),
  m6 = c(60, 68),
  M6 = c(60, 69),
  m3 = c(60, 63),
  # perfect intervals
  P5 = c(60, 67),
  P4 = c(60, 65),
  P1 = c(60, 60),
  P8 = c(60, 72),
  # dissonant intervals
  tt = c(60, 66),
  M7 = c(60, 71),
  m2 = c(60, 61),
  M2 = c(60, 62),
  m7 = c(60, 70)
)
framed_intervals <- purrr::map(intervals, ~c(.x, 72))
```

# Wave Amplitude in Space and Time as Function of Wavelength and Frequency Cycle Times

```{r, echo=F, message=F, include=T, results='asis'}
num_harmonics = 2
results <- purrr::map_dfr(names(framed_intervals), function(interval_name) {
  result <- framed_intervals[[interval_name]] %>% mami.codi(
    num_harmonics = num_harmonics,
    beat_pass_filter = BEAT_PASS_FILTER$NONE,
    cochlear_amplifier_num_harmonics = 0,
    verbose=T
  )
  print(plot_space_time(1/result$time_cycles,
                        1/result$space_cycles,
                        majorness=result$majorness,
                        chord_name=interval_name))
  tibble::tibble(
    Interval = interval_name,
    Harmonics = num_harmonics,
    TimeCycles = result$time_cycles,
    SpaceCycles = result$space_cycles,
    Majorness = result$majorness,
    Dissonance = result$dissonance,
    Chord = list(framed_intervals[[interval_name]]),
  )
})

# Print the results in a knitr table for the current num_harmonics
cat("\n\n")
cat(paste("### Framed Harmonics:", num_harmonics, "\n\n"))
print(knitr::kable(results, format = "pipe",))
cat("\n\n")  # Add spacing between tables
```
