---
title: "Greatest Common Divisor"
output:
  github_document: default
always_allow_html: true
---
```{r, echo=F, message=F, include=F}
devtools::load_all(".")
source('./man/code/plot.R')
source('./man/code/utils.R')
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "../figures/GCD-"
)
knitr::opts_chunk$set(dev = 'svg')
p = RATIONAL_FRACTION_PRECISION
```

## Generalized GCD Precision

Maybe we evaluate stern brocot approximation with these limits:\

valid_min = pow(2.0, log(freq_ratio) / log(1.89))\

valid_max = pow(2.0, log(freq_ratio) / log(2.11))\

```{r, echo=F, message=F}

ratio = 880/440

valid_min = 2.0 ^ (log(880/440) / log(1.89))

valid_max = 2.0 ^ (log(880/440) / log(2.11))

C4 = hrep::midi_to_freq(60)
E4 = hrep::midi_to_freq(64)
ratio = E4 / C4

valid_min = 2.0 ^ (log(ratio) / log(2.11))

valid_max = 2.0 ^ (log(ratio) / log(1.89))

valid_max - ratio
  
variance = default_variance()
f0 = 440
pseudo_octave = 2.0
n = 2
f1 = f0 * pseudo_octave ^ log2(n)
ratio = f1 / f0
n = 4
f3 = f0 * pseudo_octave ^ log2(n)
ratio = f3 / f0
```
## P1

```{r, echo=F, message=F}
P1 = c(60) %>% hrep::sparse_fr_spectrum(num_harmonics=10)
f = P1 %>% hrep::freq()
f
```

```{r, echo=T, message=F}
f0 = gcd(f, p)$gcd
f0
```

```{r, echo=T, message=F}
f0 / min(f)
```

```{r, echo=T, message=F}
gcd(f/min(f), p)
```

## M3

```{r, echo=F, message=F}
M3 = c(60, 64) %>% hrep::sparse_fr_spectrum(num_harmonics=10)
f = M3 %>% hrep::freq()
f
```

```{r, echo=T, message=F}
f0 = gcd(f, p)$gcd
f0
```

```{r, echo=T, message=F}
f0 / min(f)
```

```{r, echo=T, message=F}
gcd(f/min(f), p)
```
