---
title: "Harmonic Number Wavelengths"
output:
  github_document: default
always_allow_html: true
---

```{r, echo=F, message=F, include=F}
devtools::load_all(".")
c(0) %>% mami.codi()
```

### JT Ratios
1.00000: Unison       1/1
1.06667: minor 2nd    16/15
1.12500: Major 2nd    9/8
1.20000: minor 3rd    6/5
1.25000: Major 3rd    5/4
1.33333: Perfect 4th  4/3
1.40625: Tritone      45/32
1.50000: Perfect 5th  3/2
1.60000: minor 6th    8/5
1.66667: Major 6th    5/3
1.80000: minor 7th    9/5
1.87500: Major 7th    15/8
2.00000: Octave       2/1

### m3 Wavelengths 4 Harmonics
```{r, echo=T}
λ = 1.1024438
ref = 0.1638792
max_λ = 1.3110340
harmonic_num = 1 / 8
     # octave_spans[i]   = floor(abs(log(x[i]/reference) / log(pseudo_octave)));
octave_span = floor(abs(log(λ/max_λ) / log(2)))
     # octave_factors[i] = pow(pseudo_octave, octave_spans[i]);
octave_factor = 2^octave_span
t = tibble::tibble(
  # ratios[i] = (x[i] / octave_factors[i]) / reference * harmonic_number;
  # pseudo_ratios[i]   = pow(2.0, log(ratios[i]) / log(pseudo_octave));
  ratio_div_har = 2 * 2^(log((λ / octave_factor) / ref * harmonic_num)/log(2)),
  period = λ,
  reference = ref,
  harmonic_num = harmonic_num,
  fraction_div_har = list(rational_fraction(.data$ratio_div_har, WAVELENGTH_TOLERANCE)),
  num_div_har = .data$fraction_div_har[[1]][1] * octave_factor,
  den_div_har = .data$fraction_div_har[[1]][2],
  octave_span,
  octave_factor,
  ratio = (λ/octave_factor)/ref,
  fraction = list(rational_fraction(.data$ratio, WAVELENGTH_TOLERANCE)),
  num = .data$fraction[[1]][1] * octave_factor,
  den = .data$fraction[[1]][2],
  ratio_har = .data$ratio * harmonic_num,
  fraction_har = list(rational_fraction(.data$ratio_har, WAVELENGTH_TOLERANCE)),
  num_har = .data$fraction_har[[1]][1] * octave_factor,
  den_har = .data$fraction_har[[1]][2]
)
t
```

### M3 Wavelengths 4 Harmonics
```{r, echo=T}
ref = 0.1638792
λ = 0.2601421
max_λ = 1.3110340
harmonic_num = 1 / 8
     # octave_spans[i]   = floor(abs(log(x[i]/reference) / log(pseudo_octave)));
octave_span = floor(abs(log(λ/max_λ) / log(2)))
     # octave_factors[i] = pow(pseudo_octave, octave_spans[i]);
octave_factor = 2^octave_span
t = tibble::tibble(
  # ratios[i] = (x[i] / octave_factors[i]) / reference * harmonic_number;
  # pseudo_ratios[i]   = pow(2.0, log(ratios[i]) / log(pseudo_octave));
  ratio_div_har = 2 * 2^(log((λ / octave_factor) / ref * harmonic_num)/log(2)),
  period = λ,
  reference = ref,
  harmonic_num = harmonic_num,
  fraction_div_har = list(rational_fraction(.data$ratio_div_har, WAVELENGTH_TOLERANCE)),
  num_div_har = .data$fraction_div_har[[1]][1] * octave_factor,
  den_div_har = .data$fraction_div_har[[1]][2],
  octave_span,
  octave_factor,
  ratio = (λ/octave_factor)/ref,
  fraction = list(rational_fraction(.data$ratio, WAVELENGTH_TOLERANCE)),
  num = .data$fraction[[1]][1] * octave_factor,
  den = .data$fraction[[1]][2],
  ratio_har = .data$ratio * harmonic_num,
  fraction_har = list(rational_fraction(.data$ratio_har, WAVELENGTH_TOLERANCE)),
  num_har = .data$fraction_har[[1]][1] * octave_factor,
  den_har = .data$fraction_har[[1]][2]
)
t
```

### M3 Wavelengths 4 Harmonics
```{r, echo=T}
ref = 0.1638792
λ = 1.0405683
max_λ = 1.3110340
harmonic_num = 1 / 8
     # octave_spans[i]   = floor(abs(log(x[i]/reference) / log(pseudo_octave)));
octave_span = floor(abs(log(λ/max_λ) / log(2)))
     # octave_factors[i] = pow(pseudo_octave, octave_spans[i]);
octave_factor = 2^octave_span
t = tibble::tibble(
  # ratios[i] = (x[i] / octave_factors[i]) / reference * harmonic_number;
  # pseudo_ratios[i]   = pow(2.0, log(ratios[i]) / log(pseudo_octave));
  ratio_div_har =  2^(log((λ / octave_factor) / ref * harmonic_num)/log(2)),
  period = λ,
  reference = ref,
  harmonic_num = harmonic_num,
  fraction_div_har = list(rational_fraction(.data$ratio_div_har, WAVELENGTH_TOLERANCE)),
  num_div_har = .data$fraction_div_har[[1]][1] * octave_factor,
  den_div_har = .data$fraction_div_har[[1]][2],
  octave_span,
  octave_factor,
  ratio = (λ/octave_factor)/ref,
  fraction = list(rational_fraction(.data$ratio, WAVELENGTH_TOLERANCE)),
  num = .data$fraction[[1]][1] * octave_factor,
  den = .data$fraction[[1]][2],
  ratio_har = .data$ratio * harmonic_num,
  fraction_har = list(rational_fraction(.data$ratio_har, WAVELENGTH_TOLERANCE)),
  num_har = .data$fraction_har[[1]][1] * octave_factor,
  den_har = .data$fraction_har[[1]][2]
)
t
```

### m3 M6 Ratios
```{r, echo=T}
C4f  = 261.6256
Eb4f = 311.1270
A4f  = 440.0000
C5f  = 523.2511

C4w  = SPEED_OF_SOUND / C4f
Eb4w = SPEED_OF_SOUND / Eb4f
A4w  = SPEED_OF_SOUND / A4f
C5w  = SPEED_OF_SOUND / C5f

tibble::tibble(
  jm3f = 6 / 5,
  m3f  = Eb4f / C4f,
  m3w  = C4w / Eb4w,
  dM6w = A4w / C5w,
  jM6f = 5 / 3,
  dm3w = Eb4w / C5w,
  M6f  = A4f / C4f,
  M6w  = C4w / A4w,
  C4f,
  Eb4f,
  A4f,
  C5f,
  C4w,
  Eb4w,
  A4w,
  C5w
)
```

### M6 Wavelengths 2 Harmonics
```{r, echo=T}
ref = 1.311034
λ = 0.7795455
harmonic_num = 1 / 4
octave_span = floor(log(ref/λ) / log(2))
octave_factor = 2^octave_span
t = tibble::tibble(
  ratio = ref / (λ) * harmonic_num,
  fraction = list(rational_fraction((1 / .data$ratio) / octave_factor, WAVELENGTH_TOLERANCE)),
  num = .data$fraction[[1]][1],
  den = .data$fraction[[1]][2],
  pre = ref / λ,
  pre_harm = (1 / (ref / λ * harmonic_num)) / 2,
  pseudo_raw = 1 / .data$pre,
  raw_ratio = list(rational_fraction(1 / .data$pseudo_raw, WAVELENGTH_TOLERANCE)),
  raw_num = .data$raw_ratio[[1]][1],
  raw_den = .data$raw_ratio[[1]][2],
  λ,
  ref,
  octave_span,
  octave_factor
)
t
```

### M3 Wavelengths 2 Harmonics
```{r, echo=T}
ref = 1.311034
λ = 1.0405683
harmonic_num = 1 / 4
octave_span = floor(log(ref/λ) / log(2)) + 1
octave_factor = 2^octave_span
t = tibble::tibble(
  just_P5 = 3 / 2,
  et_P5 = 2^(7/12),
  pre = ref / λ,
  pre_harm = (1 / (ref / λ * harmonic_num)) / 2,
  pseudo_raw = 1 / .data$pre,
  raw_ratio = list(rational_fraction(1 / .data$pseudo_raw, WAVELENGTH_TOLERANCE)),
  raw_num = .data$raw_ratio[[1]][1],
  raw_den = .data$raw_ratio[[1]][2],
  ratio = ref / (λ) * harmonic_num,
  fraction = list(rational_fraction((1 / .data$ratio) / octave_factor, WAVELENGTH_TOLERANCE)),
  num = .data$fraction[[1]][1],
  den = .data$fraction[[1]][2],
  λ,
  ref,
  octave_span,
  octave_factor
)
t
```

### M3 Wavelengths
```{r, echo=T}
ref = 1.311034
λ = 1.0405683
harmonic_num = 1 / 6
octave_span = floor(log(ref/λ) / log(2))
octave_factor = 2^octave_span
t = tibble::tibble(
  just_m6 = 8 / 5,
  et_m6 = 2^(8/12),
  pre_harm = 1 / (ref / λ * harmonic_num),
  pre = ref / λ,
  raw = .data$pre,
  pseudo_raw = 1 / .data$raw,
  raw_ratio = list(rational_fraction(1 / .data$pseudo_raw, WAVELENGTH_TOLERANCE)),
  raw_num = .data$raw_ratio[[1]][1],
  raw_den = .data$raw_ratio[[1]][2],
  ratio = ref / (λ * octave_factor) * harmonic_num,
  fraction = list(rational_fraction(1 / .data$ratio, WAVELENGTH_TOLERANCE)),
  num = .data$fraction[[1]][1] * octave_factor,
  den = .data$fraction[[1]][2],
  λ,
  ref,
  octave_span,
  octave_factor
)
t
```

### Frequencies
```{r, echo=T}
ref = 261.6256
f = 1245.9141
octave_span = floor(log(f/ref) / log(2))
octave_factor = 2^octave_span
harmonic_num = 1
t = tibble::tibble(
  ratio = ( f / octave_factor) / ref  * harmonic_num,
  fraction = list(rational_fraction(.data$ratio, FREQUENCY_TOLERANCE)),
  num = .data$fraction[[1]][1] * octave_factor,
  den = .data$fraction[[1]][2]
)
t
```

### Wavelengths
```{r, echo=T}
ref = 1.311034
λ = 0.4129498
harmonic_num = 1 / 6
octave_span = floor(log(ref/λ) / log(2))
octave_factor = 2^octave_span
t = tibble::tibble(
  ratio = ref  / (λ * octave_factor) * harmonic_num,
  fraction = list(rational_fraction(1 / .data$ratio, WAVELENGTH_TOLERANCE)),
  num = .data$fraction[[1]][1] * octave_factor,
  den = .data$fraction[[1]][2],
  λ,
  ref,
  octave_span,
  octave_factor
)
t
```

### Other Stuff

```{r, echo=T}
tibble::tibble(
  h = (12-1:11) %>% sort(),
  λ = SPEED_OF_SOUND / hrep::midi_to_freq(60) / .data$h
)
```

```{r, echo=T}
t = tibble::tibble(
  tolerance = 0.01,
  ratio = 0.6555170 / 0.1191849 / 11,
  rounded = round(.data$ratio / (tolerance * 10)) * (tolerance * 10),
  fraction = list(rational_fraction(rounded, .data$tolerance)),
  num = .data$fraction[[1]][1],
  den = .data$fraction[[1]][2]
)
t
t$fraction
```
```{r, echo=T}
t = tibble::tibble(
  tolerance = 0.01,
  ratio = 0.4370113 / 0.1191849 / 11,
  # rounded = round(.data$ratio / (tolerance * 10)) * (tolerance * 10),
  rounded = .data$ratio,
  fraction = list(rational_fraction(rounded, .data$tolerance)),
  num = .data$fraction[[1]][1],
  den = .data$fraction[[1]][2]
)
t
t$fraction
```
```{r, echo=T}
rational_fraction(1/3, 0.00001)
```
```{r, echo=T}
t = tibble::tibble(
  ratio = 1.311034 / 0.4370113 * 0.04545455,
  fraction = list(rational_fraction(.data$ratio, TOLERANCE)),
  num = .data$fraction[[1]][2],
  den = .data$fraction[[1]][1]
)
t
```
```{r, echo=T}
t = tibble::tibble(
  ratio = 1.311034  / 0.4129498 * 0.1666667,
  fraction = list(rational_fraction(1 / .data$ratio, WAVELENGTH_TOLERANCE)),
  num = .data$fraction[[1]][1],
  den = .data$fraction[[1]][2]
)
t
```
