## The Math

### Quantum Consonance Perception

#### Temporal

$$\psi(\omega, t) = \int \phi(k) e^{-i \left( \omega t - k x \right) } dk$$

#### Spatial

$$\phi(k, t) = \int \psi(\omega, t) e^{-i \left( k x \right) } d\omega$$

#### Uncertainty

The model is quantized and the uncertainty is introduced when converting wavlength 
and frequency ratios to rational fractions using the Stern-Brocot tree with 
variance $\sigma^2$.

$$\Delta \omega \Delta k \ge \frac{1} {2}$$

$${\sigma_f}^2 {\sigma_\lambda}^2 \ge \frac{1} {16 \pi^2}$$

#### The Fundamentals

    * A series of tones is sounded for an infinite amount of time.
    * The state of a tone ratio is described by a Stern-Brocot (SB) function 
    which is the probability of the tone ratio's rational fraction approximation.
        * Tone ratios are quantized.
        * The SB distribution has variance $\sigma^2$.
        * The integral of the SB probability distribution is 1.
    * The fundamental tone of a series of tones is the ALCD of the ratios of 
    the series relative to the minimum tone. 
    * There are two series of tone ratios for each series of sounded tones.
        * Wavelength ratios
        * Frequency ratios
    * Wavelength and frequency ??? (ratios, fundamentals, values?) are conjugates.
    * The variances of the period and frequency variance are governed by 
    the generalized uncertainty principle.
    
    
#### The Wave Equation

$$\psi(x,t) = e^{ i \left(\omega t - k x \right)}$$

#### de Broglie Waves

$$\psi(x,t) = e^{ - \left( i / \hbar \right) \left(E t - p x \right)}$$

$$\omega = E / \hbar$$

$$E = p^2 / 2 m$$

$$\psi(x,t) = e^{ -i \left(\omega t - p x / \hbar \right)}$$

$$k = p / \hbar$$

$$\psi(x,t) = e^{ -i \left(\omega t - k x \right)}$$

#### Free Wave Packets

$$\psi(x,t) = \int \phi(p) e^{-\left(i/\hbar \right) \left( E t - p x \right) } dp$$

$$\psi(x,t) = \int \phi(\hbar k) e^{-\left(i/\hbar \right) \left( \omega \hbar t - k \hbar x \right) } dp$$

$$\psi(x,t) = \int \phi(\hbar k) e^{-i \left( \omega t - k x \right) } dk\hbar$$



#### Time

Once the chord is sounded and present in the cochlea, if we freeze time we still
have a period detector. Hair cells in the neighborhood of the period 
might be in vraious positions depending on the phase of the wave when we freeze
time but the sensors still gives us all the information.\

In frozen time, though, the frequency sensor does us no good. It doesn't have
any information to share with us.\

See J.L. Basdevant Lectures 5.1.3 Stationary States and Eq. 5.8.



#### Stern Brocot

Consonance perception of a chord with multiple partials is both a wave and a 
probabilistic phenomenon.

The probabilistic aspect comes from approximating rational numbers within a given 
variance using the Stern-Brocot tree.

```{r, child=c('man/SternBrocotCurve.Rmd')}
```

#### Free Wave Packets

$$\psi(x,t) = e^{-i \left( \pmb{\omega} t - \pmb{k} x \right) }$$

$$\phi(\pmb{k})=\frac{1}{\sqrt{2 \pi}} \int e^{-i \pmb{k} \pmb{\omega}}\psi(\pmb{\omega})d^N \omega $$

$\pmb{\omega}$ and $\pmb{k}$ are vectors of length $N$.

#### Fourier Transform

$$\psi(\pmb{\omega})=\frac{1}{\sqrt{2 \pi}} \int e^{i \pmb{k} \pmb{\omega}}\phi(\pmb{k})d^N k$$

$$\phi(\pmb{k})=\frac{1}{\sqrt{2 \pi}} \int e^{-i \pmb{k} \pmb{\omega}}\psi(\pmb{\omega})d^N \omega $$

$\pmb{\omega}$ and $\pmb{k}$ are vectors of length $N$.

#### Now Make $\psi$ and $\phi$ work

$\psi$ is frequency, the probability of the fundamental frequency.\

$\phi$ is period, the probability of the fundamental period.\



#### Real Traveling Wave


$$\psi(x,t) = \sin \left( \frac{2\pi x}{\lambda_{0}} - 2 \pi f_{0} t \right)$$

#### Complex Traveling Wave

$$\psi(x,t) = e ^ {-i\left( 2 \pi f_{0} t - \frac{2\pi x}{\lambda_{0}} \right)}$$

#### State of the Chord

At time $t$ the probability for the chord to be in a given state is given by

$$dP(x) = |\psi(x,t)|^2dx$$
It's a probability so the integral must be one:

$$P(x)=\int|\psi(x,t)|^2dx=1 $$

### Thoughts

$f(x)$ and $g(x)$ are both probabilities. The product of their variance satisfies
the uncertainty principle.\

So what are they in our model?\

$f_{0}(f_{i \dots N})$ and $\lambda_{0}(\lambda_{i \dots N})$ are probabilities 
that a set of frequencies or periods will have a specific fundamental value.\

