---
title: "Frequency and Wavelength Relative Periodicity"
output:
  github_document: default
---

# Chord Cycle Estimates

```{r, echo=F, message=F, warning=F}
devtools::load_all('.')
setwd('.')
source('./man/code/plot.R')
source('./man/code/utils.R')
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

```{r, echo=F, results='asis'}
midi  = c(0,4,7) + 60
tolerance = 0.15
chord = midi %>% mami.codi(
  frequency_tolerance     = tolerance,
  wavelength_tolerance = tolerance,
  verbose=T,
  num_harmonics=1
)
midi
```

## Spatial

```{r, echo=F, results='asis', message=F}
knitr::kable(tibble::tibble(
  tol_l   = chord$wavelength_tolerance,
  min_l   = min(chord$wavelengths[[1]]),
  lcd_l   = chord$wavelength_lcd,
  chord_l = min_l * lcd_l,
  chord_T = chord_l / SPEED_OF_SOUND
  # chord_T = chord_l / SPEED_OF_SOUND * max(chord$wavelengths[[1]])/min_l
))
```

```{r, echo=F, results='asis', message=F}
ratios = chord$wavelength_ratios[[1]] %>%
  dplyr::select(index, num, den, tone)
lcd    = chord$wavelength_lcd
plot_periodicity(ratios, lcd, 'space', log2_scale = F)
```

## Temporal
```{r, echo=F, results='asis', message=F}
knitr::kable(tibble::tibble(
  tol_f   = chord$frequency_tolerance,
  min_f   = min(chord$frequencies[[1]]),
  lcd_f   = chord$frequency_lcd,
  chord_T = lcd_f / min_f / (max(chord$frequencies[[1]])/min(chord$frequencies[[1]]))
))
```

```{r, echo=F, results='asis', message=F}
ratios = chord$frequency_ratios[[1]] %>% 
  dplyr::select(index, num, den, tone)
lcd    = chord$frequency_lcd
plot_periodicity(ratios, lcd, 'time', log2_scale = F)
```

### Wavelength Ratios

```{r, echo=F, results='asis', message=F}
knitr::kable(chord$wavelength_ratios[[1]] %>% dplyr::arrange(ratio) %>% dplyr::select(-pseudo_ratio))
```

### Frequency Ratios
```{r, echo=F, results='asis', message=F}
knitr::kable(chord$frequency_ratios[[1]] %>% dplyr::arrange(ratio) %>% dplyr::select(-pseudo_ratio))
```

## References
[Periodic function from Wikipedia](https://en.wikipedia.org/wiki/Periodic_Tunction)
