---
title: "Working Through Wavelength Ratios"
output:
  github_document: default
always_allow_html: true
---

```{r, echo=F, message=F, include=F}
devtools::load_all(".")
source('../code/plot.R')
c(0) %>% mami.codi()
```

```{r, echo=T}
chord = c(60, 64, 72) %>% mami.codi(verbose=T, num_harmonics=11)
```

```{r, echo=F}
chord %>% dplyr::select(consonance_dissonance, major_minor)
chord$chord_span
chord$tolerance_window_frequency
```

#### Frequency

```{r, echo=F}
chord$ratios_frequency[[1]] %>% dplyr::arrange(ratio) %>% dplyr::rename(freq=pitch) %>% dplyr::mutate(
  wavelength = SPEED_OF_SOUND / freq,
  harmonic_number = 1 / harmonic_number
) %>% dplyr::select(-pseudo_ratio, -wavelength)
```

```{r, echo=F}
chord$ratios_frequency[[1]]$reference[1]
chord$consonance_frequency
chord$fundamentals_span
chord$ratios_frequency[[1]]$den
lcm(chord$ratios_frequency[[1]]$den)
```

#### Wavelength


```{r, echo=F}
chord$ratios_wavelength[[1]] %>% dplyr::arrange(dplyr::desc(ratio)) %>% dplyr::rename(wavelength=pitch) %>% dplyr::mutate(
  freq = SPEED_OF_SOUND / wavelength,
  reference = SPEED_OF_SOUND / reference,
  harmonic_number
) %>% dplyr::select(den, num, ratio, freq, reference, harmonic_number)
```

```{r, echo=F}
SPEED_OF_SOUND / chord$ratios_wavelength[[1]]$reference[1]
chord$consonance_wavelength
chord$fundamentals_span
chord$ratios_wavelength[[1]]$num
lcm(chord$ratios_wavelength[[1]]$num)
```
