---
title: "Frequency and Wavelength Relative Periodicity"
output:
  github_document: default
---

## Chord

```{r, echo=F, results='asis', message=F}
devtools::load_all('.')
setwd('.')
source('./man/code/plot.R')
source('./man/code/utils.R')
midi  = c(0, 4, 7) + 60
tolerance = 1e-01
chord = midi %>% mami.codi(
  frequency_tolerance  = tolerance,
  wavelength_tolerance = tolerance,
  verbose=T,
  num_harmonics = 1
)
midi
```

### Cycles Estimates

#### Spatial Estimate
```{r, echo=F, results='asis', message=F}
knitr::kable(tibble::tibble(
  tol_l    = chord$wavelength_tolerance,
  min_l_m  = min(chord$wavelengths[[1]]),
  max_l_m  = max(chord$wavelengths[[1]]),
  chord_Sz = chord$wavelength_lcd,
  chord_m  = min_l_m * chord_Sz,
  chord_s  = chord_m / SPEED_OF_SOUND * (max_l_m / min_l_m),
  chord_Hz = 1 / chord_s,
) %>% dplyr::select(chord_Hz, chord_m, chord_s, chord_Sz))
```

```{r, echo=F, results='asis', message=F}
ratios = chord$wavelength_ratios[[1]] %>%
  dplyr::select(index, num, den, tone)
lcd    = chord$wavelength_lcd
plot_periodicity(ratios, lcd, 'wavelength')
```

##### Wavelength Ratios
```{r, echo=F, results='asis', message=F}
knitr::kable(chord$wavelength_ratios[[1]] %>% dplyr::arrange(ratio) %>% dplyr::select(-pseudo_ratio))
```

#### Temporal Estimate
```{r, echo=F, results='asis', message=F}
knitr::kable(tibble::tibble(
  tol_f    = chord$frequency_tolerance,
  min_f_Hz = min(chord$frequencies[[1]]),
  max_f_Hz = max(chord$frequencies[[1]]),
  chord_Sz = chord$frequency_lcd,
  chord_Hz = min_f_Hz / chord_Sz,
  chord_s  = 1 / chord_Hz,
  chord_m  = SPEED_OF_SOUND / chord_Hz
) %>% dplyr::select(chord_Hz, chord_m, chord_s, chord_Sz))
```

```{r, echo=F, results='asis', message=F}
ratios = chord$frequency_ratios[[1]] %>% 
  dplyr::select(index, num, den, tone)
lcd    = chord$frequency_lcd
plot_periodicity(ratios, lcd, 'frequency')
```

#### Frequency Ratios
```{r, echo=F, results='asis', message=F}
knitr::kable(chord$frequency_ratios[[1]] %>% dplyr::arrange(ratio) %>% dplyr::select(-pseudo_ratio))
```

## References
[Periodic function from Wikipedia](https://en.wikipedia.org/wiki/Periodic_Tunction)
