---
title: "Amplitude Search"
output:
  github_document: default
always_allow_html: true
---

```{r, echo=F}
search_label = 'Rolloff2'
```

# `r search_label`

```{r, echo=F, message=F, include=F}
devtools::load_all(".")
source('../code/plot.R')
source('../code/utils.R')
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "../figures/amplitude_lower_bound_search/"
)
knitr::opts_chunk$set(dev = 'png')
```

```{r, echo=F}
BEHAVIOURAL_SMOOTH_BROAD  <- 0.2
search_params = tibble::tibble(
  search       = c('Rolloff2','Rolloff7','Rolloff12'),
  roll_off     = c(2,7,12),
  sigma        = BEHAVIOURAL_SMOOTH_BROAD,
  gray_vlines  = list(0:15),
  black_vlines = c(list(c(3,4,5,7,8,9,12)),
                   list(c(4,5,6,7,9,12)),
                   list(c(3,4,5,7,8,9,12)))
)
params = search_params %>% dplyr::filter(search==search_label)
```

```{r, echo=F}
experiment.csv = paste0('../data/',
                        'roll_off_', params$roll_off,
                        '.csv')

experiment = read.csv(experiment.csv) %>%
  dplyr::rename(
    consonance_dissonance = rating,
    semitone              = interval
  )

theory.rds = paste0('../data/amplitude_lower_bound_',
                    search_label,
                    '.rds')
theory = readRDS(theory.rds)

```

```{r, echo=F, results='asis', message=F}
theory <- theory %>% dplyr::rowwise() %>% dplyr::mutate(
  num_harmonics  = metadata$num_harmonics,
  octave_ratio   = metadata$octave_ratio,
  semitone       = metadata$semitone,
  roll_off_dB    = metadata$roll_off_dB,
  .before=1
) %>% dplyr::group_by(amplitude_lower_bound)
```

Sounded Amplitudes:
```{r, echo=F}
sounded_amps = theory$spectrum[[1]] %>% hrep::amp() %>% unique
sounded_amps
```

MaMi.CoDi Minimum Amplitudes:
```{r, echo=F}
amps = theory$amplitude_lower_bound %>% unique
amps
```

Number of Harmonics:
```{r, echo=F}
theory$num_harmonics %>% unique
```

Octave Ratios:
```{r, echo=F}
theory$octave_ratio %>% unique
```

Roll Offs:
```{r, echo=F}
theory$roll_off_dB %>% unique
```

Precisions:
```{r, echo=F}
theory$variance %>% unique
```


```{r, echo=F}
z_scores <- function(x) {
  sd = sd(x)
  if (sd == 0) {
    0
  }  else {
    (x-mean(x)) / sd(x) 
  }
}
smoothing_file = './tests/notes/code/smooth_2d_gaussian.cpp'
if (file.exists(smoothing_file))  {
  Rcpp::sourceCpp(smoothing_file)
} else {
  Rcpp::sourceCpp('../code/smooth_2d_gaussian.cpp')
}
smoothed <- function(x,val,sigma=BEHAVIOURAL_SMOOTH_BROAD) {
  y = rep(0.0, times = length(x))
  smooth_2d_gaussian(
    data_x   = x,
    data_y   = y,
    data_val = val,
    probe_x  = x,
    probe_y  = y, 
    sigma_x  = sigma,
    sigma_y  = sigma
  )
}
```

```{r, echo=F}
cols = 1
rows = length(amps)
```

## CoDi

```{r _CoDi, fig.height=7*rows, fig.width=12*cols, echo=F}
# height = 3 per row and width = 5 per column
# so for grid of 4x12 it would be height=12 and width=60
theory <- theory %>% 
  dplyr::mutate(
    z_score = z_scores(consonance_dissonance),
    smooth  = smoothed(semitone, .data$z_score, params$sigma)
  )

plot_semitone_codi_wrap_amp(
  theory, 
  experiment,
  gray_vlines  = params$gray_vlines[[1]],
  black_vlines = params$black_vlines[[1]],
  title=paste(search_label),
  ncols=cols,
  include_points=T
)
```
