---
title: "Framed Dyads"
output:
  github_document: default
---

```{r, echo=F, message=F, include=F}
devtools::load_all(".")
source('../code/plot.R')
source('../code/utils.R')
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/framed_dyads_",
  warning = FALSE, 
  message = FALSE
)
BEHAVIOURAL_SMOOTH_BROAD  <- 0.2
BEHAVIOURAL_SMOOTH_NARROW <- 0.035
```

### Manipulating harmonic frequencies

```{r, include=F}
framed_dyads = readRDS('../data/framed_dyads.rds')
```

```{r, include=F}
dyads <- framed_dyads %>% dplyr::rowwise() %>% dplyr::mutate(
  type          = metadata$type,
  num_harmonics = metadata$num_harmonics,
  octave_ratio  = metadata$octave_ratio,
  semitone      = metadata$semitone,
  scale         = metadata$scale,
  label         = round(metadata$semitone),
  chord_max     = max(frequencies),
  chord_min     = min(frequencies),
  .before=1
)
```

```{r, fig.height=8, fig.width=12, echo=F, results='asis', message=F}
params = list(
  list(h=10,o=2.0,s='macro'),
  list(h=5, o=2.0,s='macro'),
  list(h=5,o=2,s='5PartialsNo3'),
  list(h=1, o=2.0,s='Pure'),
  list(h=10,o=2.1,s='macro'),
  list(h=10,o=1.9,s='macro'),
  list(h=4,o=2,s='Bonang'),
  list(h=10,o=2.0,s='M3'),
  list(h=10,o=2.0,s='M6'),
  list(h=10,o=2.0,s='P8')
)

p = params %>% purrr::map(\(p) {
  gray_vlines = c()
  black_vlines = c()
  description = ''
  if (p$o==2 & p$h==10 & p$s == 'macro') {
    timbre = 'Harmonic'
    black_vlines  = c(2,3,4,5,7,8,9,12)
    description   = '   For 10 harmonics, behavioral results and theoretical predictions agree.'
  } else if (p$o==2 & p$h==5 & p$s == 'macro') {
    timbre = '5Partials'
    black_vlines  = c(3,4,5,7,9,12,14)
    description = '  For 5 harmonics, behavioral results and theoretical predictions agree. For comparison with the study below (5 partils with the third partial deleted), notice that the m3 peak is only slightly lower than the M3 peak.'
  } else if (p$o==2 & p$h==5 & p$s == '5PartialsNo3') {
    timbre = '5PartialsNo3'
    black_vlines  = c(4,5,7,9,12,14)
    description = '  For 5 harmonics with the 3rd partial deleted, behavioral results and theoretical predictions mostly agree. As expected, the m3 peak without the third partial is now lower than the m3 peak with all 5 harmonics while the M3 peak is slightly higher without the 3rd partial.'
  } else if (p$o==2 & p$h==1 & p$s == 'Pure') {
    timbre = 'Pure'
    black_vlines  = c(7,12)
    description = '  For pure tones, the behavioral results and the theoretical predictions mostly agree. Only P5 and P8 have pronounced two-sided peaks. The behavioral results show subtle variations in consonance height across the 15 semitones but the overall peak structure agrees with MaMi.CoDi predictions. For futher comparison, the theoretical predictions for major-minor versus the behavioral results are included in a plot below.'
  } else if (p$o>2 & p$s == 'macro') {
    timbre = 'Stretched'
    black_vlines  = c(4.2,7.5,9.3,12.78)
    description = '  For stretched harmonics, behavioral results and theoretical predictions mostly agree. MaMi.Codi predicts peaks with minor polarity just above m3 and m7 that do not exist in the behavioral results.'
  } else if (p$o<2 & p$s == 'macro') {
    timbre = 'Compressed'
    black_vlines  = c(3.8,4.8,11.1,14.5)
    description = '  For compressed harmonics, the pronounced behavioral peaks mostly agree with the theoretical peaks.'
  } else if (p$s == 'Bonang') {
    timbre = 'Bonang'
    black_vlines = c(2.60, 4.80, 11.98)
    gray_vlines  = c(7.2, 9.6)
    description = "  For gamalan dyads with a harmonic bass pitch and bonang upper pitch, behavioral results and theoretical predictions mostly agree. MaMi.CoDi predicts a dissonance trough with minor polarity at P4 that is not in the behavioral results.  MaMi.CoDi predicts P5 to have minor polarity and be relatively higher than the behavioral results."
  } else if (p$s == 'M3') {
    timbre = 'M3'
    gray_vlines = c(hrep::freq_to_midi(hrep::midi_to_freq(60) * 5/4)-60,4,4.092442)
    black_vlines  = c(3.95)
    description = '  Description is below.'
  } else if (p$s == 'M6') {
    timbre = 'M6'
    gray_vlines = c(hrep::freq_to_midi(hrep::midi_to_freq(60) * 5/3)-60,9,8.66952)
    black_vlines  = c(8.78,8.93)
    description = '  Description is below.'
  } else if (p$s == 'P8') {
    timbre = 'P8'
    gray_vlines = c(hrep::freq_to_midi(hrep::midi_to_freq(60) * 2/1)-60)
    black_vlines  = c(11.94, 12.08)
    description = '  Description is below.'
  }
  title = paste(
    timbre,
    '~',
    'Partials:', p$h
  )
  
  chords <- dyads %>% dplyr::filter(num_harmonics  == p$h &
                                      octave_ratio == p$o &
                                      scale        == p$s)
  chords$consonance_dissonance_z = z_scores(chords$consonance_dissonance)
  
  experiment.rds = paste0('../data/',
                          timbre,
                          '.rds')
  
  experiment_all = readRDS(experiment.rds)
  
  experiment = experiment_all$profile %>%
    dplyr::rename(semitone=interval)
  
  experiment <- experiment %>% dplyr::mutate(
    consonance_dissonance = rating
  )
  
  experiment_raw = experiment_all$data %>% 
    dplyr::rename(semitone=interval, 
                  consonance_dissonance_z=rating)
  
  if (p$s == 'macro' | p$s == 'Bonang' | p$s == '5PartialsNo3' | p$s == 'Pure') {
    sigma = BEHAVIOURAL_SMOOTH_BROAD
  } else {
    sigma = BEHAVIOURAL_SMOOTH_NARROW
  }
  if (timbre=='Harmonic') {
    cat('  \n#### Dyads spanning 15 semitones\n')
  }
  if (timbre=='M3') {
    cat('  \n#### Dyads spanning 1 quarter tone\n')
  }
  cat("  \n#####", title, '\n')
  print(knitr::kable(tibble::tibble_row(
    detected_pseudo_octave  = paste(round(chords$pseudo_octave %>% unique, 2), collapse = ' '),
    ignore_amplitudes_below = paste(round(chords$min_amplitude %>% unique, 2), collapse = ' '),
    spatial_tolerance       = paste(round(chords$spatial_tolerance %>% unique, 5), collapse = ' '),
    temporal_tolerance      = paste(round(chords$temporal_tolerance %>% unique, 5), collapse = ' '),
    smoothing_sigma         = sigma
  )))
  print(plot_semitone_codi(chords, paste('Consonance-Dissonance'),
                           goal=experiment,sigma=sigma,
                           black_vlines=black_vlines,gray_vlines=gray_vlines))
  cat("  \n")

  print(plot_semitone_cowave.cofreq(chords, title='Spatial-Consonance Temporal-Consonance'))
  cat("  \n")

  print(plot_semitone_mami(chords, paste('Major-Minor'),
                           goal=experiment,sigma=sigma,
                           black_vlines=black_vlines,gray_vlines=gray_vlines))
  cat("  \n")

  print(plot_cofreq.cowave(chords, title='Spatial-Consonance Temporal-Consonance'))
  cat("  \n")

  print(plot_mami.codi(chords, title='Major-Minor Consonance-Dissonance'))
  cat("  \n")
})
```


# MaMi CoDi Plots

```{r, include=F}
source('../code/utils.R')

chord_types <- c('Dyads','Triads','Major Triad Progressions',
                 'Minor Triad Progressions', 'Scales')
chords <- chords %>% dplyr::filter(type %in% chord_types)

major_I = chords %>% dplyr::filter(type == 'Major Triad Progressions' &
                                     label == 'I')
minor_i = chords %>% dplyr::filter(type == 'Minor Triad Progressions' &
                                     label == 'i')

progression_tonics = list(
  'Major Triad Progressions 1' = (major_I$pitches[[1]] %>%
                                    mami.codi.R::mami.codi(num_harmonics=1))$chord[[1]],
  'Minor Triad Progressions 1' = (minor_i$pitches[[1]] %>% 
                                    mami.codi.R::mami.codi(num_harmonics=1))$chord[[1]],
  'Major Triad Progressions 5' = (major_I$pitches[[1]] %>%
                                    mami.codi.R::mami.codi(num_harmonics=5))$chord[[1]],
  'Minor Triad Progressions 5' = (minor_i$pitches[[1]] %>% 
                                    mami.codi.R::mami.codi(num_harmonics=5))$chord[[1]],
  'Major Triad Progressions 10' = (major_I$pitches[[1]] %>%
                                     mami.codi.R::mami.codi(num_harmonics=10))$chord[[1]],
  'Minor Triad Progressions 10' = (minor_i$pitches[[1]] %>% 
                                     mami.codi.R::mami.codi(num_harmonics=10))$chord[[1]]
)

```

```{r, include=F}
grid = tidyr::expand_grid(
  index         = seq_along(chords$pitches),
  num_harmonics = c(1,5,10)
)

results = grid %>% furrr::future_pmap_dfr(\(index,
                                     num_harmonics) {
  
  chord_spectrum = hrep::sparse_fr_spectrum(chords$pitches[[index]],
                                            num_harmonics = num_harmonics)
  
  if (endsWith(chords$type[index], 'Progressions')) {
    if (chords$label[index] == 'I' | chords$label[index] == 'i' | chords$label[index] == '') {
      tonic_spectrum = NULL
    } else {
      tonic_spectrum = progression_tonics[[paste(chords$type[index],num_harmonics)]]
    }
  } else {
    if (is.na(chords$tonic[[index]])) {
      tonic_spectrum = NULL
    } else {
      tonic_spectrum = hrep::sparse_fr_spectrum(chords$tonic[[index]],
                                                num_harmonics = num_harmonics)
    }
  }  
  mami.codi.R::mami.codi(chord_spectrum,
                         metadata=purrr::flatten(
                           list(chords$metadata[[index]],
                                num_harmonics=num_harmonics)
                         ),
                         verbose=T)
}, .progress=TRUE, .options = furrr::furrr_options(seed = T))

results <- results %>% dplyr::rowwise() %>% dplyr::mutate(
  label = metadata$label,
  type  = metadata$type, 
  num_harmonics=metadata$num_harmonics,
  .before=1
)
```


## Chords: Consonance-Dissonance ~ Major-Minor

```{r, echo=F, message=F, results='asis'}
for (t in chord_types) {
  
  cat("  \n###", t, '\n')
  
  for (n in results$num_harmonics %>% unique) {
    title = paste(
      t,
      '~',
      'Number of Harmonics:', n
    )
    r = results %>% dplyr::filter(
      type==t & 
        num_harmonics == n
    )
    print(plot_mami.codi(r, title, include_path=endsWith(t, 'Progressions'),
                         include_labels=T))
  }
  
  cat("  \n")
  
}
```
