---
title: "Listen for Harmonics"
output:
  github_document: default
---

```{r, echo=F, message=F, include=F}
devtools::load_all(".")
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/LISTEN-FOR-HARMONICS-"
)
```

## Major 3rd - From Below

```{r}
M3 = hrep::sparse_fr_spectrum(c(60,64), num_harmonics=10)
M3 %>% hrep::freq()
```

```{r}
C4_harmonics_w_tolerance = harmonic_series_with_tolerance(60,20,DEFAULT_OCTAVE_TOLERANCE)
C4_harmonics_w_tolerance
```

```{r}
matches=analyze_harmonics(hrep::freq(M3),hrep::freq(M3) %>% min,C4_harmonics_w_tolerance)
matches
```

```{r}
matches %>%
    dplyr::count(.data$pseudo_octave, name='num_harmonics',sort=TRUE) 
```

## Major 3rd - From Above

```{r}
M3 = hrep::sparse_fr_spectrum(c(60,64), num_harmonics=10)
M3 %>% hrep::freq()
```

```{r}
C4_harmonics_w_tolerance_above = harmonic_series_with_tolerance_above(
  M3 %>% hrep::freq() %>% max() %>% hrep::freq_to_midi(),20,DEFAULT_OCTAVE_TOLERANCE
)
C4_harmonics_w_tolerance_above
```

```{r}
matches=analyze_harmonics(hrep::freq(M3),hrep::freq(M3) %>% min,C4_harmonics_w_tolerance)
matches
```

```{r}
matches %>%
    dplyr::count(.data$pseudo_octave, name='num_harmonics',sort=TRUE) 
```

## Major 3rd - Missing Fundamental-ish

```{r}
M3 = hrep::sparse_fr_spectrum(c(60,64), num_harmonics=10)
M3 = M3 %>% dplyr::filter(x>300)
M3 %>% hrep::freq()
```

```{r}
C5_harmonics_w_tolerance = harmonic_series_with_tolerance(72,20,DEFAULT_OCTAVE_TOLERANCE)
C5_harmonics_w_tolerance
```

```{r}
matches=analyze_harmonics(hrep::freq(M3),hrep::freq(M3) %>% min,C4_harmonics_w_tolerance)
matches
```

```{r}
matches %>%
    dplyr::count(.data$pseudo_octave, name='num_harmonics',sort=TRUE) 
```

