---
title: "Tolerance Search"
output:
  github_document: default
always_allow_html: true
---

```{r, echo=F}
search_label = 'Stretched'
```

# `r search_label`

```{r, echo=F, message=F, include=F}
devtools::load_all(".")
source('../code/plot.R')
source('../code/utils.R')
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "../figures/tolerance_search/"
)
knitr::opts_chunk$set(dev = 'png')
```

```{r, echo=F}
BEHAVIOURAL_SMOOTH_BROAD  <- 0.2
BEHAVIOURAL_SMOOTH_NARROW <- 0.035

search_params = tibble::tibble(
  search       = c('Pure',
                   'Stretched','Harmonic','Compressed',
                   'Bonang','5Partials','5PartialsNo3',
                   'M3','M6','P8'),
  sigma        = c(BEHAVIOURAL_SMOOTH_BROAD,
                   BEHAVIOURAL_SMOOTH_BROAD,BEHAVIOURAL_SMOOTH_BROAD,BEHAVIOURAL_SMOOTH_BROAD,
                   BEHAVIOURAL_SMOOTH_BROAD,BEHAVIOURAL_SMOOTH_BROAD,BEHAVIOURAL_SMOOTH_BROAD,
                   BEHAVIOURAL_SMOOTH_NARROW,BEHAVIOURAL_SMOOTH_NARROW,BEHAVIOURAL_SMOOTH_NARROW),
  gray_vlines  = c(list(0:15),
                   list(0:15),list(0:15),list(0:15),
                   list((12/5)*1:6), list(c(4,5,7,9,12,14)),list(0:15),
                   list(c(hrep::freq_to_midi(hrep::midi_to_freq(60) * 5/4)-60,4,4.092442)),
                   list(c(hrep::freq_to_midi(hrep::midi_to_freq(60) * 5/3)-60,8.66952)),
                   c(hrep::freq_to_midi(hrep::midi_to_freq(60) * 2/1)-60)),
  black_vlines = c(list(c(7,12)),
                   list(c(4.2,7.5,9.3,12.78)),list(c(2,3,4,5,7,8,9,12)),list(c(3.8,4.8,11.1,14.5)),
                   list(c(2.6,4.8,12.0)),list(c(3,4,5,7,9,12,14)),list(c(4,5,7,9,12,14)),
                   list(c(3.95)),list(c(8.78,8.93)),list(c(11.94, 12.08)))
)
params = search_params %>% dplyr::filter(search==search_label)
```

```{r, echo=F}
experiment.rds = paste0('../data/',
             search_label,
             '.rds')
experiment = readRDS(experiment.rds)$profile %>% 
  dplyr::rename(semitone=interval)

experiment <- experiment %>% dplyr::mutate(
  consonance_dissonance = rating
)

theory.rds = paste0('../data/tolerance_',
                    search_label,
                    '.rds')
theory = readRDS(theory.rds)

```

```{r, echo=F, results='asis', message=F}

theory <- theory %>% dplyr::rowwise() %>% dplyr::mutate(
  num_harmonics  = metadata$num_harmonics,
  octave_ratio   = metadata$octave_ratio,
  semitone       = metadata$semitone,
  .before=1
) %>% dplyr::group_by(spatial_tolerance)
```

Tolerances:
```{r, echo=F}
tols = theory$spatial_tolerance %>% unique
tols
```

Number of Harmonics:
```{r, echo=F}
theory$num_harmonics %>% unique
```

Octave Ratios:
```{r, echo=F}
theory$octave_ratio %>% unique
```

```{r, echo=F}
z_scores <- function(x) {
  sd = sd(x)
  if (sd == 0) {
    0
  }  else {
    (x-mean(x)) / sd(x) 
  }
}
smoothing_file = './tests/notes/code/smooth_2d_gaussian.cpp'
if (file.exists(smoothing_file))  {
  Rcpp::sourceCpp(smoothing_file)
} else {
  Rcpp::sourceCpp('../code/smooth_2d_gaussian.cpp')
}
smoothed <- function(x,val,sigma=BEHAVIOURAL_SMOOTH_BROAD) {
  y = rep(0.0, times = length(x))
  smooth_2d_gaussian(
    data_x   = x,
    data_y   = y,
    data_val = val,
    probe_x  = x,
    probe_y  = y, 
    sigma_x  = sigma,
    sigma_y  = sigma
  )
}
```

```{r, echo=F}
theory <- theory %>% 
  dplyr::mutate(
    z_score = z_scores(consonance_dissonance),
    smooth  = smoothed(semitone, .data$z_score, params$sigma)
  )
```

```{r, echo=F}
cols = 1
rows = length(tols)
```

## CoDi Wrap

```{r trial, fig.height=7*rows, fig.width=12*cols, echo=F}
# height = 3 per row and width = 5 per column
# so for grid of 4x12 it would be height=12 and width=60
plot_semitone_codi_wrap(
  theory, 
  experiment, 
  gray_vlines  = params$gray_vlines[[1]],
  black_vlines = params$black_vlines[[1]],
  title=paste(search_label),
  ncols=cols,
  include_points=F
)
```
