// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ratios
DataFrame ratios(NumericVector x, const double reference_freq, const NumericVector tolerance, const double pseudo_octave, const bool invert);
RcppExport SEXP _mami_codi_R_ratios(SEXP xSEXP, SEXP reference_freqSEXP, SEXP toleranceSEXP, SEXP pseudo_octaveSEXP, SEXP invertSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< const double >::type reference_freq(reference_freqSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< const double >::type pseudo_octave(pseudo_octaveSEXP);
    Rcpp::traits::input_parameter< const bool >::type invert(invertSEXP);
    rcpp_result_gen = Rcpp::wrap(ratios(x, reference_freq, tolerance, pseudo_octave, invert));
    return rcpp_result_gen;
END_RCPP
}
// analyze_harmonics
DataFrame analyze_harmonics(const NumericVector x);
RcppExport SEXP _mami_codi_R_analyze_harmonics(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(analyze_harmonics(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mami_codi_R_ratios", (DL_FUNC) &_mami_codi_R_ratios, 5},
    {"_mami_codi_R_analyze_harmonics", (DL_FUNC) &_mami_codi_R_analyze_harmonics, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_mami_codi_R(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
