# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

stern_brocot <- function(lower_bound, x, upper_bound) {
    .Call(`_mami_codi_R_stern_brocot`, lower_bound, x, upper_bound)
}

compute_pseudo_octave <- function(fn, f0, n) {
    .Call(`_mami_codi_R_compute_pseudo_octave`, fn, f0, n)
}

approximate_harmonics <- function(x, approximate_lcm_sd) {
    .Call(`_mami_codi_R_approximate_harmonics`, x, approximate_lcm_sd)
}

approximate_pseudo_octave <- function(approximate_harmonics) {
    .Call(`_mami_codi_R_approximate_pseudo_octave`, approximate_harmonics)
}

frequency_erb <- function(frequency) {
    .Call(`_mami_codi_R_frequency_erb`, frequency)
}

wavelength_erb <- function(wavelength, speed_of_sound) {
    .Call(`_mami_codi_R_wavelength_erb`, wavelength, speed_of_sound)
}

approximate_rational_fractions <- function(x, approximate_lcm_sd, frequency, speed_of_sound = 343.0) {
    .Call(`_mami_codi_R_approximate_rational_fractions`, x, approximate_lcm_sd, frequency, speed_of_sound)
}

