# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' stern_brocot
#'
#' Approximates a floating-point number to arbitrary precision.
#'
#' @param x Number to convert to rational fraction
#' @param precision Binary search stops once the desired precision is reached
#'
#' @return A ratio of num / den
#'
#' @export
stern_brocot <- function(x, precision) {
    .Call(`_mami_codi_R_stern_brocot`, x, precision)
}

#' rational_fractions
#'
#' Approximates floating-point numbers to arbitrary precision.
#'
#' @param x Vector of floating point numbers to approximate
#' @param precision Precision for approximations
#'
#' @return A data frame of rational numbers and metadata
#'
#' @export
rational_fractions <- function(x, precision, pseudo_octave) {
    .Call(`_mami_codi_R_rational_fractions`, x, precision, pseudo_octave)
}

#' pseudo_octave
#'
#' Determine pseudo octave of all frequencies relative to lowest frequency
#'
#' @param x Chord frequencies
#'
#' @return A data frame of frequencies and pseudo_octaves
#'
#' @export
pseudo_octaves <- function(x) {
    .Call(`_mami_codi_R_pseudo_octaves`, x)
}

