# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' rational_fraction
NULL

rational_fraction <- function(x, tolerance, pseudo_octave) {
    .Call(`_mami_codi_R_rational_fraction`, x, tolerance, pseudo_octave)
}

ratios <- function(x, pseudo_octave, tolerance) {
    .Call(`_mami_codi_R_ratios`, x, pseudo_octave, tolerance)
}

compute_pseudo_octave <- function(fn, f0, n) {
    .Call(`_mami_codi_R_compute_pseudo_octave`, fn, f0, n)
}

analyze_harmonics <- function(x) {
    .Call(`_mami_codi_R_analyze_harmonics`, x)
}

